#!/bin/bash
CWD="`pwd`";

echo Monitor started.

server_healing_file="serverHealing.txt"
server_failure_log="serverFailures.txt"

echo Started self heaing.

while true;
do
	sleep 10 # Send request every 10 seconds
	for server in `cat hosts`
	do
		# Send request to server to check status
		curl -s -X GET "http://$server:1973/0" > /dev/null
		if [ $? -ne 0 ];
		then
			echo "Server $server is down"
			if ! grep -q "$server" "$server_healing_file"; then
				current_timestamp=$(date +"%Y-%m-%d %H:%M:%S")
				echo "$server is down. Current time: $current_timestamp" >> $server_failure_log
				echo "$server $current_timestamp" >> "$server_healing_file"
				./healingServers &
			fi
		else 
			echo "Server $server is up"
		fi
	done
done