#!/bin/bash

sf=$1
fb=$2
ft=$3
sm=$4
mb=$5
mt=$6
ss=$7
current_timestamp=$(date +"%Y-%m-%d %H:%M:%S")

server_healing_file="../orchestration/serverHealing.txt"
line=$(grep "$sf" "$server_healing_file")

failed_timestamp=$(echo "$line" | awk '{print $2, $3}')


./copyRangeFromTo $sm $sf $mb $mt "$failed_timestamp" "$current_timestamp"

./copyRangeFromTo $ss $sf $fb $ft "$failed_timestamp" "$current_timestamp"




